version: "3.9"

services:
  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_SERVER_HOST: ${DB_SERVER_HOST:-localhost}
      DB_SERVER_PORT: ${DB_SERVER_PORT:-8001}
      RMQ_HOST: ${RMQ_HOST:-localhost}
      RMQ_PORT: ${RMQ_PORT:-5672}
      RMQ_USER: ${RMQ_USER:-guest}
      RMQ_PASS: ${RMQ_PASS:-guest}
      RECSYS_SERVER_HOST: ${RECSYS_SERVER_HOST:-localhost}
      RECSYS_SERVER_PORT: ${RECSYS_SERVER_PORT:-8002}
    restart: unless-stopped
    depends_on: []

  consumer:
    build: .
    command: python3 consumer.py
    volumes:
      - .:/app
    restart: unless-stopped
